### ISSUE TITLE
how to manage stopRefreshing(false) without any specific delay time in OnRefreshListener

### ISSUE THREAD

**Issue by hpcreator** [SimformSolutionsPvtLtd/SSPullToRefresh#15]
First of Thank you so much team for such a beautiful library to make our animation stuff easy.

I am bit confuse about use of SwipeRefreshLayout that's why i am here to be more clear.
I want to start refreshing when I enter in the activity and want to stop refreshing when all my apis getting called and UI is updated, but as per your readme we can add specific delay to stop refreshing.  

please make us clear for this kind of scenario as this is the most common thing in apps.

**Comment by nishchal-v** [comment]
@hpcreator Thank you for appreciating the work we do.

The scenario you are requesting is not currently available in this Library. We currently only support user-driven refreshing.
And stop that when the API call/ loading/Data fetching is complete.

We are considering this as a Feature request and will add that as soon as possible

**Comment by hpcreator** [comment]
Thank you @nishchal-v-simformsolutions for clarification.
I hope you guys will add this feature soon.

**Comment by ShwetaChauhan18** [comment]
New feature request

**Comment by ShwetaChauhan18** [comment]
New feature request
