### ISSUE TITLE
Add feature to disable and enable SSPullToRefresh

### ISSUE THREAD

**Issue by vahan16** [SimformSolutionsPvtLtd/SSPullToRefresh#20]
In some cases I need to disable pull to refresh, and the library does not allow me to do that.
It would be good to have that feature to disable SSPullToRefresh.

**Comment by nishchal-v** [comment]
@vahan16 Thanks for trying out our Library!

Based on your needs, I suppose you can toggle the `View.isEnabled` on your SSPullToRefresh to disable/enable it.
Let us know if you have any other specific requirements that we can help with.

**Comment by vahan16** [comment]
Hi again **@nishchal-v** 
I have already tried with `isEnabled` and that's not working,

I just cloned your repository and tried to fix that,
and the issue can be fixed with returning false in `onInterceptTouchEvent` method

If you can add this improvement, it will be appreciated.

![Screen Shot 2023-01-25 at 12 11 20](https://user-images.githubusercontent.com/28810981/214512367-676a250f-f32a-48ac-83c1-2b22ef3e3db5.png)

**Comment by nishchal-v** [comment]
@vahan16 `isEnabled` Should work and it works while testing on the demo I have embedded in this repo, no need to provide an extra boolean flag in the  `SSPullToRefresh` class that essentially does the same.

I would like to know how you disable the `SSPullToRefresh` and why it is not working for you.
The `View.isEnabled` is primitive functionality and should work on custom views without any issues.

Can you please share more info on how you disable the view, on which android version you are testing and what the target API levels are?
