### ISSUE TITLE
Add feature to set custom view as refresh view

### ISSUE THREAD

**Issue by javichaques** [SimformSolutionsPvtLtd/SSPullToRefresh#24]
Hi, I would like the possibility of adding a custom view as refresh view.
In my case I need to be able to add a button with localized texts.

**Comment by nishchal-v** [comment]
Hello @javichaques , Thanks for using our library.

Let me see what can be done in terms of your specific requirements. The refresh view is not meant to be interactive and it is just presentable view, representing the Lotties animations or other kinds of loading presentations.
Still I'll look in to the possibilities and if possible, would provide this functionality.

Thanks for collaboration, Happy coding.

**Comment by nishchal-v** [comment]
@javichaques Your requested feature would now be available in the version `1.5`.

Please review the attached PR description for simplest usage.

**Comment by javichaques** [comment]
Thanks @nishchal-v it works perfectly. The only thing is that it does not take the height of the custom view, but you have to indicate it with setRefreshViewParams
