### ISSUE TITLE
wrong behavior with app bar

### ISSUE THREAD

**Issue by BoikoIlya** [SimformSolutionsPvtLtd/SSPullToRefresh#38]
if i have screen with coordinatorLayout  appBar and collapsingToolbar in it and  SSPullToRefreshLayout with recycler in it and this attiribute  app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior"

and the problem is: when you half collapse app bar and scroll up refresh is triggers, but it shouldnt, and app bar shoud fully expand.
how to solve this issue?

**Comment by nishchal-v** [comment]
Thank you for using **SSPullToRefresh**.
We'll try to reproduce this on our end and update the fix accordingly.

**Comment by BoikoIlya** [comment]
i can attach example layout and video

**Comment by nishchal-v** [comment]
@BoikoIlya Sure, that would be helpful to debug the issue, please do share

**Comment by nishchal-v** [comment]
@BoikoIlya Please share your xml and any setup that you have done programatically which is significant to reproduce this issue.

**Comment by BoikoIlya** [comment]
> @BoikoIlya Please share your xml and any setup that you have done programatically which is significant to reproduce this issue.

`
<?xml version="1.0" encoding="utf-8"?>

<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/coordiantor"
    >

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        >

    <com.google.android.material.appbar.CollapsingToolbarLayout
        android:id="@+id/toolBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_scrollFlags="scroll|enterAlways"
        android:background="@color/white_lightBlack"
        app:contentScrim="@android:color/transparent"
        >
        <androidx.constraintlayout.widget.ConstraintLayout
            android:paddingBottom="10dp"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingHorizontal="20dp"
            >

            <ImageButton
                android:visibility="gone"
                android:id="@+id/back_btn"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginEnd="10dp"
                android:background="?android:attr/selectableItemBackgroundBorderless"
                android:src="@drawable/left_chevron"
                app:layout_constraintEnd_toStartOf="@id/textInputLayout2"
                app:layout_constraintBottom_toBottomOf="@+id/textInputLayout2"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="@+id/textInputLayout2"
                android:tint="@color/gray" />

            <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/textInputLayout2"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="25dp"
                app:endIconDrawable="@drawable/close"
                app:endIconMode="clear_text"
                app:hintEnabled="false"
                app:layout_constraintEnd_toStartOf="@id/main_menu_btn"
                app:layout_constraintStart_toEndOf="@id/back_btn"
                app:layout_constraintTop_toTopOf="parent"
                style="@style/Widget.Design.TextInputLayout"
                >

                <EditText
                    android:id="@+id/searchFavorites"
                    android:layout_width="match_parent"
                    android:layout_height="40dp"
                    android:background="@drawable/search_bg"
                    android:drawableStart="@drawable/search"
                    android:drawablePadding="10dp"
                    android:drawableTint="@color/orange"
                    android:inputType="text"
                    android:hint="@string/search_track"
                    android:textColorHint="@color/gray"
                    android:paddingStart="10dp"
                    android:textSize="@dimen/body1"
                    android:textColor="@color/black_white"
                    android:textCursorDrawable="@drawable/cursor_drawable" />
            </com.google.android.material.textfield.TextInputLayout>

            <ImageButton
                android:visibility="gone"
                android:id="@+id/main_menu_btn"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:background="?android:attr/selectableItemBackgroundBorderless"
                android:src="@drawable/setting"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintBottom_toBottomOf="@+id/textInputLayout2"
                app:layout_constraintStart_toEndOf="@id/textInputLayout2"
                app:layout_constraintTop_toTopOf="@+id/textInputLayout2"
                android:tint="@color/black_white" />

            <TextView
                android:id="@+id/title_favorites"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="20dp"
                android:text="@string/favorites_songs"
                android:textColor="@color/black_white"
                android:textSize="@dimen/h3"
                app:layout_constraintEnd_toStartOf="@+id/shuffleFavorites"
                app:layout_constraintStart_toStartOf="@+id/back_btn"
                app:layout_constraintTop_toBottomOf="@+id/textInputLayout2" />


            <ImageButton
                android:id="@+id/shuffleFavorites"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="20dp"
                android:layout_marginEnd="20dp"
                android:background="?selectableItemBackgroundBorderless"
                android:src="@drawable/shuffle_black"
                android:tint="@color/black_white"
                app:layout_constraintBottom_toBottomOf="@+id/title_favorites"
                app:layout_constraintEnd_toStartOf="@id/menu"
                app:layout_constraintTop_toBottomOf="@+id/textInputLayout2" />

            <ImageButton
                android:id="@+id/menu"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="20dp"
                android:background="?selectableItemBackgroundBorderless"
                android:src="@drawable/menu"
                android:tint="@color/black_white"
                app:layout_constraintBottom_toBottomOf="@+id/title_favorites"
                app:layout_constraintEnd_toEndOf="@+id/main_menu_btn"
                app:layout_constraintTop_toBottomOf="@+id/textInputLayout2" />
    </androidx.constraintlayout.widget.ConstraintLayout>
        </com.google.android.material.appbar.CollapsingToolbarLayout>
    </com.google.android.material.appbar.AppBarLayout>

    <com.kamancho.melisma.app.core.ScrollUpRecyclerButton
        android:id="@+id/scrollUpButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:backgroundTint="@color/black_orange"
        android:background="?attr/selectableItemBackground"
        android:src="@drawable/up_chevron"
        app:tint="@color/orange_black"
        app:shapeAppearance="@style/ThemeOverlay.Material3.FloatingActionButton.Secondary"
        android:layout_gravity="bottom|end"
        android:layout_marginBottom="160dp"
        android:layout_marginEnd="20dp"
        android:visibility="gone"
        />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior"
        >

        <TextView
            android:layout_gravity="center_horizontal"
            android:visibility="gone"
            android:layout_marginTop="35dp"
            android:id="@+id/errorMessage"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@string/no_favorite_tracks"
            android:textColor="@color/black_white"
            android:textSize="@dimen/h3"
            android:textAlignment="center"
            android:background="@color/white_lightBlack"
            />

        <com.simform.refresh.SSPullToRefreshLayout
            android:id="@+id/pull_to_refresh"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/white_lightBlack"
            >

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/favoritesRcv"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                tools:listitem="@layout/track_item"
                android:paddingBottom="140dp"
                android:clipToPadding="false"
            />
        </com.simform.refresh.SSPullToRefreshLayout>



    </LinearLayout>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
`

Here is video: https://github.com/SimformSolutionsPvtLtd/SSPullToRefresh/assets/100340546/de6acc59-c119-4a72-bffd-5e713b52d68a

when i half collapse app bar and scroll up recycler i trigger refresh but need expand app bar. it should be able trigger refresh only when app bar/collapsedToolbar fully expand.

how fast you will fix it?

**Comment by nishchal-v** [comment]
@BoikoIlya I have fixed the issue on the a separate branch and you can use the specific [commit hash](https://github.com/SimformSolutionsPvtLtd/SSPullToRefresh/commit/8f35003793af2e6c241dc54e86daead4653e163b) to check the issue is fixed or not.

**Comment by BoikoIlya** [comment]
> @BoikoIlya I have fixed the issue on the a separate branch and you can use the specific [commit hash](https://github.com/SimformSolutionsPvtLtd/SSPullToRefresh/commit/8f35003793af2e6c241dc54e86daead4653e163b) to check the issue is fixed or not.

I have never face with that before,  should i change dependency in gradle? And how?

**Comment by nishchal-v** [comment]
@BoikoIlya Refer this answer [here](https://github.com/SimformSolutionsPvtLtd/SSPullToRefresh/issues/29#issuecomment-1494490148)

**Comment by BoikoIlya** [comment]
> @BoikoIlya Refer this answer [here](https://github.com/SimformSolutionsPvtLtd/SSPullToRefresh/issues/29#issuecomment-1494490148)

yeah it is working fine, good job

**Comment by nishchal-v** [comment]
@BoikoIlya Now you can use version `1.5.2` with this issue fixed
